apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ required .Values.awsAccountId }}:role/dst-{{ required .Values.environment }}-eks-lb-role   
    eks.amazonaws.com/sts-regional-endpoints: "true"