apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ds-translator.fullname" . }}-frontend
  labels:
    app: {{ include "ds-translator.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ds-translator.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "ds-translator.name" . }}-frontend
      annotations:
        {{- toYaml .Values.frontend.annotations | nindent 8 }}          
    spec:
      nodeSelector:
        {{- toYaml .Values.frontend.nodeSelector | nindent 8 }}       
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
