apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ds-translator.fullname" . }}-backend
  labels:
    app: {{ include "ds-translator.name" . }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ds-translator.name" . }}-backend
      component: backend
  template:
    metadata:
      labels:
        app: {{ include "ds-translator.name" . }}-backend
        component: backend
    spec:
      nodeSelector:
        {{- toYaml .Values.backend.nodeSelector | nindent 8 }}    
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.stt.backend.port }}
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY
            - name: DEEPL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deepl-api-key
                  key: DEEPL_API_KEY               
            {{- with .Values.backend.env }}
            {{- if kindIs "map" . }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- else if kindIs "slice" . }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- end }}            
