apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ .Release.Name }}-gpu
spec:
  labels:
    provisioner: {{ .Values.provisionerGpu.provisioner | default "gpu" }}
  limits:
    resources:
      cpu: {{ .Values.provisionerGpu.limits.cpu | default "1000" }}
      memory: {{ .Values.provisionerGpu.limits.memory | default "2048Mi" }}
  provider:
    instanceProfile: {{ .Values.provisionerGpu.provider.instanceProfile | quote }}
    securityGroupSelector:
      karpenter.sh/discovery: {{ .Values.clusterName }}
    subnetSelector:
      karpenter.sh/discovery: {{ .Values.clusterName }}    
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values:
      {{- range .Values.provisionerGpu.requirements.instanceTypes }}
        - {{ . | quote }}
      {{- end }}
