apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 100Gi # Ignored, required
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  claimRef: # To ensure no other PVCs can claim this PV
    namespace: dev # Namespace is required even though it's in "default" namespace.
    name: model-s3-pvc # Name of your PVC
  mountOptions:
    - allow-delete
    - region us-east-1
    - prefix dev/
  csi:
    driver: s3.csi.aws.com # Required
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: dst-dev-test-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-s3-pvc
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 100Gi # Ignored, required
  volumeName: s3-pv # Name of your PV
