name: CI/CD Helm Chart Promotion Pipeline

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    env:
      FULL_DOMAIN: 'dev.dstranslator.cloud'

    name: Deploying to dev
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials for Dev
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ SECRETS.AWS_ACCOUNT_ID }}:role/dst-dev-github-deployment-role
          aws-region: ${{ SECRETS.AWS_REGION }}

      - name: Update kubeconfig for Dev
        run: aws eks update-kubeconfig --region ${{ SECRETS.AWS_REGION }} --name dst-dev-cluster

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Helm Lint
        run: helm lint ./helm/ds-translator

      - name: Render Templates (Helm Template)
        run: helm template dev-ds-translator ./helm/ds-translator --namespace dev --values ./helm/ds-translator/values-dev.yaml

      - name: Dry-Run Install
        run: |
          helm upgrade --install dev-ds-translator ./helm/ds-translator \
            --namespace dev \
            --create-namespace \
            --values ./helm/ds-translator/values-dev.yaml \
            --dry-run

      - name: Create or Update API Key Secret in Dev
        run: |
          kubectl create secret generic openai-api-key \
            --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --namespace dev --dry-run=client -o yaml | kubectl apply -f -

          kubectl create secret generic deepl-api-key \
          --from-literal=DEEPL_API_KEY=${{ secrets.DEEPL_API_KEY }} \
          --namespace dev --dry-run=client -o yaml | kubectl apply -f -

      # - name: Determine Image Tag
      #   id: set_tag
      #   run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV
  

      - name: Deploy Helm Chart to Dev
        run: |
          helm upgrade --install dev-ds-translator ./helm/ds-translator \
            --namespace dev \
            --create-namespace \
            --values ./helm/ds-translator/values-dev.yaml \
      # --set image.tag=${{ env.IMAGE_TAG }}

      - name: Wait for Deployment to Stabilize
        run: sleep 10

      - name: Setting new DNS for domain
        run: |
          echo ">> Running basic connection test"
          HOSTNAME=$(kubectl get ingress dev-ds-translator-ds-translator-ingress -n dev -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "Ingress hostname: ${HOSTNAME}"
          echo "::set-output name=hostname::${HOSTNAME}"

      - name: Prepare Change Batch File
        run: |
          # Replace placeholders in the template with the actual values.
          sed -e "s/__ENVIRONMENT__/dev\./g" \
              -e "s/__TARGET__/${{ steps.get-hostname.outputs.hostname }}/g" \
              dns/change-batch.json > change-batch-temp.json
          cat change-batch-temp.json 
        env:
          FULL_DOMAIN: 'dev.dstranslator.cloud'

      - name: Wait for DNS changes
        run: sleep 10

      - name: Run Integration Tests on Dev
        run: |
          echo ">> Running basic connection test"
          curl --fail http://dev.dstranslator.cloud || exit 1
          echo "Domain and website can be reached"

  package-artifact:
    name: Package Helm Chart Artifact
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags
      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Package Helm Chart
        run: |
          TAG=$(git describe --tags --abbrev=0)
          helm package ./helm/ds-translator --version ${TAG}+${GITHUB_SHA} --destination packaged-charts

      - name: Upload Helm Chart Artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart
          path: packaged-charts/*.tgz

  promote-to-stage:
    name: Promote to Stage
    needs: package-artifact
    runs-on: ubuntu-latest
    environment: stage  # Requires manual approval via GitHub environment protection
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # - name: Create or Update API Key Secret in Stage
      #   run: |
      #     kubectl create secret generic openai-api-key \
      #       --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
      #       --namespace dev --dry-run=client -o yaml | kubectl apply -f -

      - name: Configure AWS Credentials for Stage
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ SECRETS.AWS_ACCOUNT_ID }}:role/dst-stage-github-deployment-role
          aws-region: ${{ SECRETS.AWS_REGION }}

      - name: Update kubeconfig for Stage
        run: aws eks update-kubeconfig --region ${{ SECRETS.AWS_REGION }} --name dst-stage-cluster

      - name: Set up Helm
        uses: azure/setup-helm@v1

      - name: Download Helm Chart Artifact
        uses: actions/download-artifact@v4
        with:
          name: helm-chart

      - name: Deploy Helm Chart to Stage
        run: |
          helm upgrade --install stage-ds-translator ./packaged-charts/*.tgz \
            --namespace stage \
            --create-namespace \
            --values helm/values-stage.yaml \
      # --set image.tag=${{ env.IMAGE_TAG }}

      - name: Wait for Deployment to Stabilize
        run: sleep 10

      - name: Setting new DNS for domain
        run: |
          echo ">> Running basic connection test"
          HOSTNAME=$(kubectl get ingress stage-ds-translator-ds-translator-ingress -n dev -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "Ingress hostname: ${HOSTNAME}"
          echo "::set-output name=hostname::${HOSTNAME}"

      - name: Prepare Change Batch File
        run: |
          # Replace placeholders in the template with the actual values.
          sed -e "s/__ENVIRONMENT__/stage\./g" \
              -e "s/__TARGET__/${{ steps.get-hostname.outputs.hostname }}/g" \
              dns/change-batch.json > change-batch-temp.json
          cat change-batch-temp.json 
        env:
          FULL_DOMAIN: 'stage.dstranslator.cloud'

      - name: Wait for DNS changes
        run: sleep 10

      - name: Run Integration Tests on Stage
        run: |
          echo ">> Running basic connection test"
          curl --fail http://stage.dstranslator.cloud || exit 1
          echo "Domain and website can be reached"

  # promote-to-prod:
  #   name: Promote to Prod
  #   needs: promote-to-stage
  #   runs-on: ubuntu-latest
  #   environment: prod  # Requires manual approval via GitHub environment protection
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v3

  #     - name: Create or Update API Key Secret in Prod
  #       run: |
  #         kubectl create secret generic openai-api-key \
  #           --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
  #           --namespace dev --dry-run=client -o yaml | kubectl apply -f -

  #     - name: Configure AWS Credentials for Prod
  #       uses: aws-actions/configure-aws-credentials@v2
  #       with:
  #         role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/dst-prod-github-infrastructure-role
  #         aws-region: ${{ secrets.AWS_REGION }}

  #     - name: Update kubeconfig for Prod
  #       run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name dst-prod-cluster

  #     - name: Set up Helm
  #       uses: azure/setup-helm@v1

  #     - name: Download Helm Chart Artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: helm-chart

  #     - name: Deploy Helm Chart to Prod
  #       run: |
  #         helm upgrade --install myapp-prod ./packaged-charts/*.tgz \
  #           --namespace prod \
  #           --create-namespace \
  #           --values helm/values-prod.yaml \
  #           --set image.tag=${{ env.IMAGE_TAG }}

  #     - name: Wait for Deployment to Stabilize
  #       run: sleep 15

  #     - name: Run Integration Tests on Prod
  #       run: |
  #         curl --fail http://myapp-prod.prod.svc.cluster.local/health || exit 1
  #         echo "Prod tests passed"
